### ISSUE TITLE
histogram max initial value

### ISSUE THREAD

**Issue by jstypka** [Feuerlabs/exometer#111]
The initial value for the histogram max datapoint is 0 which does not work when operating on negative numbers. Can it be changed to -infinity or something similar (with calculating min of negative values)?

https://github.com/Feuerlabs/exometer/blob/master/src/exometer_histogram.erl#L187

**Comment by tolbrino** [comment]
@jstypka @mpmiszczyk Please move this discussion over to https://github.com/Feuerlabs/exometer_core if it is still needed.
