### ISSUE TITLE
build is failing on 17.3

### ISSUE THREAD

**Issue by benoitc** [Feuerlabs/exometer#115]
I get the following wrror whil ebuilding exometer on latest Erlang release:

    Compiling /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl failed:
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:51: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:408: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:445: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:446: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:476: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:477: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:482: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:483: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:488: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    /Users/benoitc/work/exometer/deps/meck/src/meck_proc.erl:489: type dict/0 is deprecated and will be removed in OTP 18.0; use use dict:dict/0 or preferably dict:dict/2
    ERROR: compile failed while processing /Users/benoitc/work/exometer/deps/meck: rebar_abort

This is an error in meck itself but wanted to also report it there.

**Comment by tolbrino** [comment]
Closing this since all builds are green.
