### ISSUE TITLE
Unexpected behavior with fast_counter

### ISSUE THREAD

**Issue by jpuigm** [Feuerlabs/exometer#123]
Hi,

I'm testing out `fast_counter` metric type with `exometer`, and experiencing unexpected behavior:

```erlang
> erl -pa ebin -pa deps/*/ebin -s exopose_app 
Erlang/OTP 17 [erts-6.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V6.2.1  (abort with ^G)
1> 16:02:07.712 [info] Application lager started on node nonode@nohost
16:02:07.731 [info] Application exometer started on node nonode@nohost
16:02:07.735 [info] Application exopose started on node nonode@nohost

1> exopose:i().
[...]
2> dbg:tracer(), dbg:p(all,c), dbg:tp(exopose, i, x).
{ok,[{matched,nonode@nohost,1},{saved,x}]}
3> exometer:new([test,fastcounter], {function, exopose, i, [], fast_counter, value}, []).
ok
4> (<0.77.0>) call exopose:i()
(<0.77.0>) exception_from {exopose,i,0} {exit,{timeout,{gen_server,call,[exopose,info]}}}
```

I've omitted what `exopose:i/0` returns for simplicity, but my point is that, after creating `fast_counter` providing `exopose` and `i` as module and function, `erlang:trace_pattern/3` leaves the call non-responsive. Am I misusing the feature or there's a potential issue? 

As a side note, `exometer:create_entry/1` returns ok if I launch the dbg, but I can't see anything printed out if I trace down `exometer:set_call_count/3`, i.e: https://github.com/Feuerlabs/exometer/blob/master/src/exometer.erl#L1070

Thanks,

**Comment by uwiger** [comment]
The way you create the metric is odd.

```erlang
1> exometer:start().
08:42:43.365 [info] Application lager started on node nonode@nohost
08:42:43.390 [info] Starting reporters with []
ok
08:42:43.390 [info] Application exometer_core started on node nonode@nohost
2> exometer:new([fc], fast_counter, [{function,{c,pwd}}]).
ok
3> exometer:get_value([fc]).
{ok,[{value,0},{ms_since_reset,9983}]}
4> pwd().
/Users/uwiger/FL/git/exometer_core
ok
5> exometer:get_value([fc]).
{ok,[{value,1},{ms_since_reset,14679}]}
6> pwd().
/Users/uwiger/FL/git/exometer_core
ok
7> exometer:get_value([fc]).
{ok,[{value,2},{ms_since_reset,21111}]}
```

I think a clarification in the documentation might be in order. Also, the `exometer_function` module should probably do more validation. What you're doing is effectively creating a function metric with an invalid specification.

Note that fast counters rely on the built-in tracing functionality, so if you try to trace on functions that are being used as fast counters, results are likely to be confusing. In this case, exometer would change the trace pattern for the function, so you will not get the call trace printout you expect:

```erlang
1> exometer:start().
09:01:12.476 [info] Application lager started on node nonode@nohost
09:01:12.510 [info] Starting reporters with []
ok
09:01:12.510 [info] Application exometer_core started on node nonode@nohost
2> dbg:tracer(), dbg:tp(c,pwd,x), dbg:p(all,[c]).
{ok,[{matched,nonode@nohost,55}]}
3> pwd().
(<0.32.0>) call c:pwd()
/Users/uwiger/FL/git/exometer_core
(<0.32.0>) returned from c:pwd/0 -> ok
ok
4> exometer:new([fc],fast_counter,[{function,{c,pwd}}]).
ok
5> pwd().                                               
/Users/uwiger/FL/git/exometer_core
ok
```

If you create the fast counter first, then set a call trace, you will disable the counter instead.

**Comment by tolbrino** [comment]
@jpuigm Is this still an open issue for you?

**Comment by tolbrino** [comment]
Closing this. Feel free to report this again if it is still an issue.
