### ISSUE TITLE
Difficulty with "very dynamic" subscriptions.

### ISSUE THREAD

**Issue by emauton** [Feuerlabs/exometer#124]
I want to export data for a set of LevelDB instances. Each has a dynamic name (here a Riak partition number) and a possibly changing set of levels. Here's what I think *should* work, from the docs:

    % LevelDB statistics per partition and level, e.g.
    % [leveldb, files, Partition, Level]
    %   files: number of files
    % We set a default for the "leveldb" tree of names, and subscribe using
    % wildcards. These variables should then be created per-partition and per-level.
    true = exometer_admin:set_default([leveldb, '_'], gauge, [{module, exometer}]),
    ok = exometer_report:subscribe(exometer_report_graphite,
                                   {find, [leveldb, files]},
                                   [value], ?INTERVAL, [], true),
    % ... further subscriptions for size, compaction time, compaction read/write size, etc.

Unfortunately, this doesn't seem to do the trick: while the entries are created, the subscription never happens:

    > exometer_report:list_metrics([leveldb, files]).
    {ok,[{[leveldb,files,
           479555224749202520035584085735030365824602865664,0],
          [value,ms_since_reset],
          [],enabled},
          {[leveldb,files,
           479555224749202520035584085735030365824602865664,1],
          [value,ms_since_reset],
          [],enabled}]}

From various tinkering in the console with exometer_report:subscribe/6, it seems that the only way to make this work is to fully specify the entry, e.g.

    [leveldb, files, 479555224749202520035584085735030365824602865664, 0]

Am I misunderstanding how this should work?

**Comment by emauton** [comment]
Sorry, missing step after the first code block is e.g.
    ok = exometer:update_or_create([leveldb, files, Partition, Level], Files),
This does result in the entries being created properly.

**Comment by uwiger** [comment]
Not sure. Here's an example:

```erlang
Eshell V5.10.3  (abort with ^G)
1> exometer:start().
23:20:22.723 [info] Application lager started on node nonode@nohost
23:20:22.763 [info] Starting reporters with []
ok
23:20:22.764 [info] Application exometer_core started on node nonode@nohost
2> exometer:new([a,b],counter,[]).
ok
3> exometer_admin:set_default([a,'_'],counter,[]).
true
4> exometer_report:add_reporter(r,[{module,exometer_report_tty}]).
ok
5> 23:20:54.411 [info] exometer_report_tty([{module,exometer_report_tty}]): Starting

5> exometer_report:subscribe(r,{find,[a]},[value],10000,[],true).
ok
6> exometer_report_tty: a_b_value 1422397283:0 (unknown)
     
6> exometer:update([a,b],3).
ok
7> exometer_report_tty: a_b_value 1422397293:3 (unknown)
exometer_report_tty: a_b_value 1422397303:3 (unknown)
exometer_report_tty: a_b_value 1422397313:3 (unknown)
7> exometer:update_or_create([a,c],3).
ok
8> exometer_report_tty: a_b_value 1422397323:3 (unknown)
exometer_report_tty: a_c_value 1422397323:3 (unknown)
exometer_report_tty: a_b_value 1422397333:3 (unknown)
exometer_report_tty: a_c_value 1422397333:3 (unknown)

```

**Comment by emauton** [comment]
Thanks for this example, I'll tinker with it tomorrow and see if I can replicate my problem.

**Comment by emauton** [comment]
Yes, confirmed that this works fine:
    exometer:start().
    exometer_admin:set_default([a, '_'], gauge, [{module, exometer}]).
    exometer_report:add_reporter(r, [{module, exometer_report_tty}]).
    exometer_report:subscribe(r, {find, [a]}, [value], 10000, [], true).
    exometer:update_or_create([a, b], 10).

The same structure applied to my original variables works fine too.

It's not clear to me what I was doing wrong, but in any case I've worked around it in my application by creating a function similar to exometer:update_or_create/4 that manages the subscription at point of creation, if necessary.

Thanks for your time!
