### ISSUE TITLE
Reporter's erlang:send_after/3 fails under heavy load

### ISSUE THREAD

**Issue by jstypka** [Feuerlabs/exometer#125]
When performing some heavier computations with many processes, I noticed that the reporter skips some of the logs. For example after running a program for 30s and logging data every 1s, the reporter ends up logging only 15 of them or sometimes even less.

In my opinion using `send_after/3` might be the issue. Reporter uses it to indicate the moment when it should activate, fetch appropriate data and "report it". Every time he receives the message `{report, Key, Interval}` he performs some action and then calls `send_after/3` once again. However when there are many other processes waiting to be scheduled, a significant amount of time may pass between the event of receiving the message, and the reporter being activated by the scheduler to process it and call the function once again. Therefore even though the interval is officially 1s, the period between the events of calling `send_after/3` might be much more than 1s. This offset accumulates over time resulting in a significant deviation in the logs.

This issue might be solved by substituting `send_after/3` with `send_interval/3`, which doesn't require resetting the timer every 1s (or whatever the interval is).

**Comment by tolbrino** [comment]
Hmm, good catch. Using `send_interval/3` would improve the situation where the offset accumulates, however it won't affect the individual offset of each timer event message when there is a overload scenario.

Did you run the same tests with `send_interval/3`? Can you provide some results?

**Comment by uwiger** [comment]
I have a proposed solution for this in exometer_core, PR [#4](https://github.com/Feuerlabs/exometer_core/pull/4):

This change adjusts timers before restarting them, based on a reference timestamp taken immediately upon reception of the timeout message. (There is of course a possibility of drift between sending and receiving the timeout message).

**Comment by magnusfeuer** [comment]
I believe this is a better solution since we will limit the number of 
messages that goes into the mailbox to 1. With send_interval/3 we will 
just keep stuffing the queue with new messages, regardless of how slow 
those messages are consumed.

For what it's worth...
/Magnus F.

**Comment by uwiger** [comment]
Also, we don't restart the timer if the reporter is disabled. It is of course possible to stop an interval timer there ...

**Comment by jstypka** [comment]
Thanks everyone for a quick response.

@tolbrino Unfortunately we didn't run exometer with `send_interval/3`, however before switching to exometer we have used a custom-made logger and experienced identical issues, which we solved by using `send_interval/3`. I don't recall having problems with flooding the inbox, the interval would have to be very short - we used 1s and it worked fine.

@uwiger The solution proposed handles the delay of processing the message, however, as you said, it doesn't adjust the time between the moment when the message is sent and the moment when the reporter is activated and may start processing messages. And this delay seems to be much more significant when there are many processes with a lot of work.

I tried to test the performance with the changes that you've made and I didn't notice any major differences - the number of logs produced even dropped slightly, although I'm not sure if it's all due to this change.

Have you considered adding a timestamp to the `{report...}` message to indicate the moment that it was scheduled to be send? This way we would know when to send the following message.

**Comment by uwiger** [comment]
Yes, I did consider it, but decided not to go there, at least for the first attempt.

I've pushed a modification that includes the interval and timestamp in the timeout msg, and these are then used to adjust the next interval. Please give it a try.

**Comment by jstypka** [comment]
Works like a charm, the number of logs is constant no matter the load. Thanks @uwiger and everybody!

**Comment by uwiger** [comment]
Thank you, @jstypta - it's great to get this kind of help from users.
