### ISSUE TITLE
Starting app using exometer crashes in exometer_folsom_monitor

### ISSUE THREAD

**Issue by youngkin** [Feuerlabs/exometer#129]
Context: Application is using rebar and relx. Including exometer and recon.

Retrieving tagged version 1.1 using rebar I get the following error on app startup:

2015-02-11 11:05:49.657 [error] <0.91.0> CRASH REPORT Process <0.91.0> with 0 neighbours exited with reason: call to undefined function setup:find_env_vars(exometer_folsom_monitor) in gen_server:init_it/6 line 330
2015-02-11 11:05:49.657 [error] <0.87.0> Supervisor exometer_sup had child exometer_folsom_monitor started with exometer_folsom_monitor:start_link() at undefined exit with reason call to undefined function setup:find_env_vars(exometer_folsom_monitor) in context start_error
2

**Comment by uwiger** [comment]
Building 1.1 with rebar:

```erlang
Testing u.exometer: TEST COMPLETE, 27 ok, 0 failed of 27 test cases

uwair:exometer uwiger$ ERL_LIBS=`pwd`/deps erl -pa ebin
Erlang R16B02 (erts-5.10.3) [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V5.10.3  (abort with ^G)
1> exometer:start().
22:40:12.791 [info] Application lager started on node nonode@nohost
22:40:12.817 [info] Starting reporters with []
ok
22:40:12.817 [info] Application exometer started on node nonode@nohost
2> setup:find_env_vars(exometer_folsom_monitor).
[]
```

It seems as if `setup` is not in your path for some reason.

**Comment by youngkin** [comment]
Hi Ulf - hopefully this isn't too much of a newbie question, what is the <code>setup</code> module and where might I find it?

**Comment by uwiger** [comment]
If the dependencies have been fetched, e.g. using `rebar get-deps`, it should be in exometer/deps/setup/ebin/.

[Setup](https://github.com/uwiger/setup) is a component that helps with building boot scripts, managing upgrades, finding environment variables, etc. In Exometer, it is used to allow applications to configure a exometer aspects in their own environment space, e.g. using the variable `exometer_folsom_monitor`.

**Comment by youngkin** [comment]
Thanks for the explanation. This dependency is indeed missing from my deps/exometer directory.

My application Makefile does indeed call <code>rebar get-deps</code>, but this apparently isn't applied recursively. This leads to another question, how to recursively apply <code>get-deps</code> to dependent applications? But this is a question more appropriate for more googling or erlang-questions. Thanks for helping me work through this!

**Comment by uwiger** [comment]
Do you have exometer or exometer_core in your application's deps?

**Comment by youngkin** [comment]
Yes (and no, I reverted to an earlier version of exometer, more below(1)). One interesting thing I noted is that all of the deps got pulled up to the <code>deps</code> directory (e.g., <code>deps/setup</code>). I expected to see them under each of the projects (e.g., <code>deps/exometer/setup</code>. I'm relatively new to <code>rebar</code> so I don't know if that's significant/normal or not. I'm also relatively new to <code>relx</code>, so I'm confused as to why <code>setup</code> wasn't included in the path.

I'm also wrestling with version mismatches for the ampq library. It looks like something in the exometer (v1.1) dependencies graph is pulling ampq in (presumably the amqp reporter) and it's incompatible with the amqp version I'm using(2). I reverted to an exometer version used by Brian Troutwine in his stress_exometer project on bitbucket(3) and that fixed both the amqp version mismatch and the <code>setup</code> issue. But I'm seeing odd behavior with using the histogram and statsd. In a nutshell, min, max, mean, and median all have the same values.

This is probably more than you asked for, thanks for reading this far.

(1) {exometer, ".*", {git, "https://github.com/Feuerlabs/exometer.git", {tag, "bd282739819bb6bf104ae2f8db433e980492956c"}}}
(2) Discussion around dependency conflicts using <code>rebar</code> - http://erlang.org/pipermail/erlang-questions/2014-April/078754.html
(3) https://bitbucket.org/troutwine/stress_exometer

**Comment by uwiger** [comment]
That exometer version is quite old.

If you're not using the amqp reporter, you can exclude those deps using the EXOMETER_PACKAGES environment variable.

**Comment by youngkin** [comment]
Yes, I definitely want to upgrade. Thanks for the advice on EXOMETER_PACKAGES, that'll help me get around to upgrading sooner.
