### ISSUE TITLE
dependency on erlang-snmp

### ISSUE THREAD

**Issue by rspring999** [Feuerlabs/exometer#131]
Initially this problem arose while attempting to install zotonic.
The "make" would fail at exometer.
So I focused on exometer specifically.
.../temp/exometer

make
=====================
...
==> Entering directory `/home/rodger/temp/exometer/deps/jiffy'
==> jiffy (compile)
==> Leaving directory `/home/rodger/temp/exometer/deps/jiffy'
==> Entering directory `/home/rodger/temp/exometer/src'
==> src (compile)
==> Leaving directory `/home/rodger/temp/exometer/src'
==> exometer (compile)
make: *** [compile] Error 1
=====================

rebar -vvv compile
=====================
==> exometer (compile)
DEBUG: Matched required ERTS version: 5.10.4 -> .*
DEBUG: Matched required OTP release: R16B03 -> .*
DEBUG: is_app_available, looking for App exometer_core with Path "/home/rodger/temp/exometer/deps/exometer_core"
INFO:  Looking for exometer_core-.* ; found exometer_core-1.0-13-g1527a82 at /home/rodger/temp/exometer/deps/exometer_core
DEBUG: is_app_available, looking for App exometer_collectd with Path "/home/rodger/temp/exometer/deps/exometer_collectd"
INFO:  Looking for exometer_collectd-.* ; found exometer_collectd-f75e680 at /home/rodger/temp/exometer/deps/exometer_collectd
DEBUG: is_app_available, looking for App netlink with Path "/home/rodger/temp/exometer/deps/netlink"
INFO:  Looking for netlink-.* ; found netlink-1 at /home/rodger/temp/exometer/deps/netlink
DEBUG: is_app_available, looking for App amqp_client with Path "/home/rodger/temp/exometer/deps/amqp_client"
INFO:  Looking for amqp_client-.* ; found amqp_client-3.3.5 at /home/rodger/temp/exometer/deps/amqp_client
DEBUG: is_app_available, looking for App jiffy with Path "/home/rodger/temp/exometer/deps/jiffy"
INFO:  Looking for jiffy-.* ; found jiffy-0.13.3 at /home/rodger/temp/exometer/deps/jiffy
DEBUG: Starting 3 compile worker(s)
DEBUG: Worker exited cleanly
DEBUG: Worker exited cleanly
DEBUG: Worker compilation failed: [{error,
                                    {'EXIT',
                                     {undef,
                                      [{snmpc,compile,
                                        ["mibs/EXOMETER-MIB.mib",
                                         [{outdir,"priv/mibs"},
                                          {i,["priv/mibs"]}]],
                                        []},
                                       {rebar_erlc_compiler,compile_mib,3,
                                        [{file,"src/rebar_erlc_compiler.erl"},
                                         {line,277}]},
                                       {rebar_base_compiler,compile,3,
                                        [{file,"src/rebar_base_compiler.erl"},
                                         {line,115}]},
                                       {rebar_base_compiler,compile_worker,3,
                                        [{file,"src/rebar_base_compiler.erl"},
                                         {line,176}]}]}}},
                                   {source,"mibs/EXOMETER-MIB.mib"}]
=====================

The solution

sudo apt-get install erlang-snmp

Likely the solution is obvious to most users of exometer but for me exometer is one of many dependencies for zotonic and it took me a while before finding my solution.

**Comment by tolbrino** [comment]
@rspring999 The SNMP reporter was conceived with using Kerl or something which provides all of OTP in mind. Obviously the way Debian et al package OTP breaks this. As far as I now there is no good solution to this, other than manually looking up the exometer dependencies and making sure the relevant OTP apps are installed locally.

**Comment by rspring999** [comment]
Thanks for the infoTino.
I added my experience to the site simply on the notion that if I had this type of problem then maybe others would also be having the problem (mainly inexperienced people like myself).
