### ISSUE TITLE
counter not incrementing?

### ISSUE THREAD

**Issue by comtihon** [Feuerlabs/exometer#139]
I use 1.2 tag and this code (exometer is started with app):

    exometer:new([the, test], counter).
    ok
    exometer:update([the, test], 4).
    ok
    exometer:info(the, test], value).
    []
Also, without update result is the same:

    exometer:new([bla, bla], counter).
    ok
    exometer:info([bla, bla]).
    [{name,[bla,bla]},
     {type,counter},
     {behaviour,undefined},
     {module,exometer},
     {status,enabled},
     {cache,0},
     {value,[]},
     {timestamp,192799789183},
     {options,[]},
     {ref,undefined},
     {datapoints,[value,ms_since_reset]}]
It is strange, as I can see in `exometer:create_entry/1` default 0 for counters.

**Comment by uwiger** [comment]
The bug is in exometer:info(Entry, value).

```erlang
2> exometer:new([the,test],counter).
ok
3> exometer:update([the,test],4).
ok
4> exometer:info([the,test]).
[{name,[the,test]},
 {type,counter},
 {behaviour,undefined},
 {module,exometer},
 {status,enabled},
 {cache,0},
 {value,[]},
 {timestamp,192803693580},
 {options,[]},
 {ref,undefined},
 {datapoints,[value,ms_since_reset]}]
5> exometer:get_value([the,test]).
{ok,[{value,4},{ms_since_reset,29662}]}
6> exometer:info([the,test], value).
[]
```

The manual for exometer:info/2 says:
> value - The result of get_value(Name)

This is obviously not what happens above.

**Comment by comtihon** [comment]
ok, thanks!
