### ISSUE TITLE
how to create rps metrics

### ISSUE THREAD

**Issue by comtihon** [Feuerlabs/exometer#140]
Hi, I want to create rps metrics. 
My first idea was to made exometer counter with time:span 1 sec, but it wont span.
Second idea (worse, I think) is to create exometer_spiral with time span 1 sec and add values 1 to it, so it can sum rps.
Another way is to create timer outside exometer for reseting counter every second. But I wonder - is there a way of creating metrics for rps?

**Comment by uwiger** [comment]
Well, you could write your own probe callback. A sketch can be found here:

https://gist.github.com/uwiger/38b5f0d9b234222ebb95

It's a fairly basic example. I've outlined some possible improvements.

**Comment by comtihon** [comment]
Could you please give me an example of creating a spiral?

**Comment by uwiger** [comment]
I'm not sure what exactly you're asking for, but:

```erlang
2> exometer:new([s], spiral, [{time_span, 10000}]).
ok
3> [begin exometer:update([s], 3), timer:sleep(100) end || _ <- lists:seq(1,100)].
[ok,ok,ok,ok,ok,ok,ok|...]
4> exometer:get_value([s]).
{ok,[{count,300},{one,264}]}
5> exometer:get_value([s]).
{ok,[{count,300},{one,234}]}
6> exometer:get_value([s]).
{ok,[{count,300},{one,147}]}
7> [begin exometer:update([s], 3), timer:sleep(100) end || _ <- lists:seq(1,100)].
[ok,ok,ok,ok,ok,ok,ok,ok|...]
8> exometer:get_value([s]).
{ok,[{count,600},{one,270}]}
```

So `count` gives the total "counter" value, while `one` gives the value for the latest time_span.

**Comment by comtihon** [comment]
Thanks!
