### ISSUE TITLE
Working support for r18

### ISSUE THREAD

**Issue by StoneCypher** [Feuerlabs/exometer#141]
Installation of `exometer` invokes `parse_trans` 2.9 instead of 2.9.2, which in turn invokes `edown` 0.5 instead of 0.8.  `edown` does not work in erlang r18 until 0.8.

I can't figure out this library's custom build process, so I haven't submitted a repair to bump a version.

**Comment by StoneCypher** [comment]
End result is that when I get to the `rebar` compile step, which works as desired in r17, instead here I get

    ==> edown (compile)
    Compiled src/edown_make.erl
    Compiled src/edown_lib.erl
    Compiled src/edown_xmerl.erl
    Compiling /Users/jhaugeland/projects/MongooseIM/deps/edown/src/edown_doclet.erl failed:
    /Users/jhaugeland/projects/MongooseIM/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
    /Users/jhaugeland/projects/MongooseIM/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
    ERROR: compile failed while processing /Users/jhaugeland/projects/MongooseIM/deps/edown: rebar_abort

**Comment by drobakowski** [comment]
Hi @StoneCypher, I had the same problem and got it running under our temporary fork https://github.com/synlay/exometer/tree/feature/release/1.2. The main problem is the outdated dependency version of `exometer_core` 1.2, which implies the `parse_trans` version 2.9. I had to update to the latest version 1.4 which implies `parse_trans` version 2.9.2. `exometer_collectd` also references `exometer_core` with the version 1.2, wherefore I also had to update `exometer_core` to 1.4. The last problem was `netlink` which had some Erlang/OTP 18.x compiling errors, but these errors should already be fixed by now on the latest master. As I wasn't sure about the exactly impact of `exometer_core` version update to 1.4, `exometer_collectd` and `netlink` I haven't created a PR so far. Maybe @uwiger or some other team member has a better overview about these updates?

**Comment by StoneCypher** [comment]
@drobakowski - I'm not sure how to reference your work.  

The closest I got was `{exometer, ".*", {git, "git://github.com/synlay/exometer.git", {ref, "3ec3f85"}}},`

I tried making a ref call and got

```
Pulling exometer from {git,"git://github.com/synlay/exometer.git",
                           {ref,"3ec3f85"}}
Cloning into 'exometer'...
ERROR: 'get-deps' failed while processing /Users/jhaugeland/projects/MongooseIM: {'EXIT',{badarg,[{io_lib,format,
                         ["git checkout -q ~s",[{ref,"3ec3f85"}]],
                         [{file,"io_lib.erl"},{line,168}]},
                 {rebar_deps,download_source,2,
                             [{file,"src/rebar_deps.erl"},{line,569}]},
                 {rebar_deps,use_source,3,
                             [{file,"src/rebar_deps.erl"},{line,508}]},
                 {rebar_deps,'-get-deps/2-fun-0-',2,
                             [{file,"src/rebar_deps.erl"},{line,184}]},
                 {lists,foldl,3,[{file,"lists.erl"},{line,1262}]},
                 {rebar_deps,'get-deps',2,
                             [{file,"src/rebar_deps.erl"},{line,183}]},
                 {rebar_core,run_modules,4,
                             [{file,"src/rebar_core.erl"},{line,490}]},
                 {rebar_core,execute,6,
                             [{file,"src/rebar_core.erl"},{line,415}]}]}}
make: *** [deps] Error 1
```

**Comment by drobakowski** [comment]
@StoneCypher are you using `rebar` or `rebar3`? I'm not sure but I think `ref` is only supported from `rebar3`. When using `rebar` you should try it without the `ref`:
```
,{exometer, ".*", {git, "git://github.com/synlay/exometer.git", "3ec3f85"}}
```

**Comment by StoneCypher** [comment]
aha, thanks :+1: 

mostly i use rebar3 but i'm hacking around a rebar2 project here

**Comment by tolbrino** [comment]
@StoneCypher #143 should fix compilation under OTP 18.x. Can you verify this?

**Comment by StoneCypher** [comment]
i will soon.  i'm in the middle of a `kerl` install to juggle some old forked stuff.  probably today

**Comment by tolbrino** [comment]
Looks like the merged change fixed this issue. In case it still persists, feel free to re-open.

**Comment by StoneCypher** [comment]
I apologize for the slow response.  I forgot about the ticket.

Confirmed: this is a fix.  Thank you very much.
