### ISSUE TITLE
Inspect and show metrics

### ISSUE THREAD

**Issue by hwinkel** [Feuerlabs/exometer#145]
Hi,

Sorry to ask a simple question here as ticket, but is there a way to inspect/shoe metrics collected in Exometer. I mean just the "runtime" information in histograms or other datatypes in a pure Erlang way. Lets say i.e. with observer running while development and showing the values or even better charts of data.

I don't mean any reporter requires external receiver.

Many thanks.

**Comment by uwiger** [comment]
Well, there are some functions for searching metrics: `exometer:get_values(Path)`, `exometer:select(MatchSpec)`, `exometer:aggregate(MatchSpec, DataPoints)`, which can be called to extract data at runtime.

You might also want to look at the [`exometer_report_logger`](https://github.com/Feuerlabs/exometer_core/blob/master/doc/exometer_report_logger.md) module, which is basically a generic reporter which can be parameterized for different kinds of input and output. It can be used to periodically sample metrics and pass the results to a callback module, which can do anything it wants with it. You can add multiple output callbacks to the same reporter, making it somewhat reminiscent of a gen_event-style construct.

**Comment by hwinkel** [comment]
An example of how the exometer_report_logger module can be used, is in the exometer_report_SUITE.erl in exometer_core

https://github.com/Feuerlabs/exometer_core/blob/master/test/exometer_report_SUITE.erl

**Comment by hwinkel** [comment]
Fine for me, I'm going to close this to keep the issue stats clean ;-)
