### ISSUE TITLE
Erlang 19

### ISSUE THREAD

**Issue by supercodepoet** [Feuerlabs/exometer#150]
Has anyone had any luck getting exometer to compile on Erlang 19 in an elixir mix project?

**Comment by tolbrino** [comment]
Meanwhile, this should be working.

**Comment by netDalek** [comment]
I add
```
{:setup, github: "uwiger/setup", manager: :rebar, override: true},
{:meck, tag: "~> 0.8.4", override: true},
```

from https://github.com/uwiger/setup/issues/24 to make it working with erlang 19.3 and elixir 1.2.4

**Comment by netDalek** [comment]
Does exometer-core really need all this dependencies? Is it possible to remove it to some rebar3 profile
