### ISSUE TITLE
erl_first_files is not working correct

### ISSUE THREAD

**Issue by roland-karlsson-erlang-solutions-com** [Feuerlabs/exometer#60]
NOTE - this bug is after applying the pull request "Fix OTP 17". How this is treated before I have no idea.

I am not sure if this is a rebar problem or some problem in the build settings for exometer.

In rebar 2.2.0 the file EXOMETER-MIB is distributed to all ebin directories in dependencies when running "make". This behaviour disappears if the section erl_first_files is removed from the rebar.config.

In rebar 2.3.0 the same thing happens. But, apart from that, if you run make more than once, you get the following crash.

==> afunix (compile)
Compiling /Users/roland/Projects/wombat/git/exometer/deps/afunix/src/exometer_util.erl failed:
/Users/roland/Projects/wombat/git/exometer/deps/afunix/src/exometer_util.erl:none: no such file or directory
ERROR: compile failed while processing /Users/roland/Projects/wombat/git/exometer/deps/afunix: rebar_abort
make: *** [compile] Error 1

This seems to be, more or less, the same thing. It also disappears if you comment away the erl_first_files section.

**Comment by uwiger** [comment]
I believe this is fixed?

**Comment by tolbrino** [comment]
I can't reproduce it either.
